### PR TITLE
parse unspents from helloblock

### PR DESCRIPTION
**Pull request by lkang**
also remove carbonwallet.js which is not used. 

Not tested yet!!

It needs to be modified to have a mainnet/testnet switch and then transaction tested.

btw, the spec dir is nearly empty....

### CODE REVIEW

**Comment by taariq** [comment]
@lkang thank you for this change. I was just asking @sidazhang about unspents using helloblock. I think this is something I can definitely test tonight.

**Comment by lkang** [comment]
whoa, dont test it on the mainnet!  better get it onto testnet first.

**Comment by taariq** [comment]
Who¹s afraid of losing a little money? Hehehe

**Comment by lkang** [comment]
I'm paranoid about that kindof thing. if you have a 50.01 btc account and you try to transfer .01 it might seem safe, but if the change output isnt right then 50 btc can disappear.

**Comment by lkang** [comment]
mb try transferring just .001 into one of the addresses in the wallet, that would be low risk.

**Comment by taariq** [comment]
Good 'nuff for me! Will get to it! Yeah!

**Comment by sidazhang** [comment]
@taariq thou shalt never test with mainnet 

not impressed!

**Comment by taariq** [comment]
@sidazhang.  Amen! You are right.

Is there a way we can implement a Testnet switch on the wallet?

Also, you guys should know that I¹m presenting this wallet at Boost VC today
for a quick pitch! Let you know how it goes!

**Comment by taariq** [comment]
@sidazhang and @lkang look at what I did! Yep. Sent 0.001 BTC to my HD wallet addy! Yeah!

```
bitcoind decoderawtransaction 010000000197d62db427e05cb3a8ccb891dd6bde9ca282e1c84e1a76da3708fe0ed1b40f72000000008c493046022100ef3c569d2641fb9efcc8c2cdc5b2a835187aa1ae6406f236f368c63347f26287022100b555f9ea02a0ca182e97eafbbfcc101864da53da0807ab835014bc6e7883bc0201410479d089d9bb15b193a0e6d5865753a6a630fd8a2fcca50529cb0aa50c41ca0726f998dda531cf9d96d3c9b5d34fc5bb3928a212d632322d5dc25fc5a18401ce8dffffffff02a0860100000000001976a914fdadbf607db9eb05760ee610b04d715787b926c688ac4fe12201000000001976a914cbfd9ac6682ff3c81cf2ba745d4a5c65cb58dde988ac00000000
{
    "txid" : "805d0c417b54f93fae55d42d3a5b8262b9ced4675a33131e96be44c561950426",
    "version" : 1,
    "locktime" : 0,
    "vin" : [
        {
            "txid" : "720fb4d10efe0837da761a4ec8e182a29cde6bdd91b8cca8b35ce027b42dd697",
            "vout" : 0,
            "scriptSig" : {
                "asm" : "3046022100ef3c569d2641fb9efcc8c2cdc5b2a835187aa1ae6406f236f368c63347f26287022100b555f9ea02a0ca182e97eafbbfcc101864da53da0807ab835014bc6e7883bc0201 0479d089d9bb15b193a0e6d5865753a6a630fd8a2fcca50529cb0aa50c41ca0726f998dda531cf9d96d3c9b5d34fc5bb3928a212d632322d5dc25fc5a18401ce8d",
                "hex" : "493046022100ef3c569d2641fb9efcc8c2cdc5b2a835187aa1ae6406f236f368c63347f26287022100b555f9ea02a0ca182e97eafbbfcc101864da53da0807ab835014bc6e7883bc0201410479d089d9bb15b193a0e6d5865753a6a630fd8a2fcca50529cb0aa50c41ca0726f998dda531cf9d96d3c9b5d34fc5bb3928a212d632322d5dc25fc5a18401ce8d"
            },
            "sequence" : 4294967295
        }
    ],
    "vout" : [
        {
            "value" : 0.00100000,
            "n" : 0,
            "scriptPubKey" : {
                "asm" : "OP_DUP OP_HASH160 fdadbf607db9eb05760ee610b04d715787b926c6 OP_EQUALVERIFY OP_CHECKSIG",
                "hex" : "76a914fdadbf607db9eb05760ee610b04d715787b926c688ac",
                "reqSigs" : 1,
                "type" : "pubkeyhash",
                "addresses" : [
                    "1Q8L6j61fpb7nRXLvxpW7Bz3Qy7xqLWtxV"
                ]
            }
        },
        {
            "value" : 0.19063119,
            "n" : 1,
            "scriptPubKey" : {
                "asm" : "OP_DUP OP_HASH160 cbfd9ac6682ff3c81cf2ba745d4a5c65cb58dde9 OP_EQUALVERIFY OP_CHECKSIG",
                "hex" : "76a914cbfd9ac6682ff3c81cf2ba745d4a5c65cb58dde988ac",
                "reqSigs" : 1,
                "type" : "pubkeyhash",
                "addresses" : [
                    "1KbbyhT3dPAMEGfVx9siDtKATLpk9vjQkW"
                ]
            }
        }
    ]
}
```

**Comment by taariq** [comment]
@sidazhang @lkang whos ya daddy? https://helloblock.io/transactions/805d0c417b54f93fae55d42d3a5b8262b9ced4675a33131e96be44c561950426

**Comment by lkang** [comment]
I created another branch which implements testnet and creates a transaction - I havent made it a pull request because I still need to test sending it to the testnet.  But all testnet addresses are generated.  Check out this branch: 

https://github.com/SF-Bitcoindevs/bitcoinjslib-wallet/tree/fix_transaction_construction

It will take a couple hours to finish it. By tomorrow! @taariq @sidazhang

**Comment by sidazhang** [comment]
Nice, love it!

Boom testnet!

When we launch we should have testnet thing where everyone gets demo wallet
with some preloaded testnet coins! lol

On Fri, Apr 18, 2014 at 2:32 PM, Larry Kang notifications@github.comwrote:

> I created another branch which implements testnet and creates a
> transaction - I havent made it a pull request because I still need to test
> sending it to the testnet. But all testnet addresses are generated. Check
> out this branch:
> 
> https://github.com/SF-Bitcoindevs/bitcoinjslib-wallet/tree/fix_transaction_construction
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/SF-Bitcoindevs/bitcoinjslib-wallet/pull/9#issuecomment-40846360
> .

## 

Kind regards,

Sidney Zhang

Mobile: +1 415 767 8831

**Pull request merged**
